<?php

function shift_cipher_menu() {
  $items = array();
  $items['shift_cipher'] = array(
    'title' => "Play Shift Cipher!",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shift_cipher_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['shift_cipher_success_page'] = array(
    'title' => "Result!",
    'page callback' => 'shift_cipher_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function shift_cipher_form() {
  $form['shift_value'] = array(
    '#title' => 'Shift Value',
    '#type' => 'textfield',
    '#description' => t('enter the number of places to shift each letter over'),
    '#element_validate' => array('element_validate_integer_positive'),
    '#required' => TRUE,
  );

  $form['shift_direction'] = array(
    '#title' => 'Shift Direction',
    '#type' => 'textfield',
    '#description' => t("enter either 'left' or 'right' for the direction you want to shift"),
    '#element_validate' => array('element_validate_direction'),
    '#required' => TRUE,
  );

  $form['shift_phrase'] = array(
    '#title' => 'Phrase to be shifted',
    '#type' => 'textfield',
    '#description' => t('enter the phrase you want to shift from'),
    // '#element_validate' => array('element_validate_phrase'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
  '#type' => 'submit',
  '#value' => 'Shift!',
  );

  return $form;
}

function element_validate_direction($element) {
  if ($element['#value'] != "left" && $element['#value'] != "right") {
    form_error($element, t('Shift Direction must be entered either "left" or "right".'));
  }
}

// function element_validate_phrase($element) {
//   $numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];
//   foreach (($element['#value']) as $character) {
//     if (in_array($character, $numbers) {
//       form_error($element, t('The phrase must only contain spaces and/or puntuations as special characters.'));
//     }
//   }
// }

function shift_cipher_form_submit($form, &$form_state) {
  $value = $form_state['values']['shift_value'];
  $direction = $form_state['values']['shift_direction'];
  $phrase = $form_state['values']['shift_phrase'];

  $lowercase_phrase = strtolower($phrase);

  $array_string = str_split($lowercase_phrase);

  $alphabets = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'];
  $output_array = array();

  foreach ($array_string as $letter) {
    if ($direction == "right") {
      if (in_array($letter, $alphabets)) {
          $key = array_search($letter, $alphabets);
          if ($key + $value > 25) {
            $shift_value = $key + $value - 26;
          } else {
            $shift_value = $key + $value;
          }
          $new_letter = $alphabets[$shift_value];
          array_push($output_array, $new_letter);
      } else {
        array_push($output_array, $letter);
      }
    } else {
      if (in_array($letter, $alphabets)) {
          $key = array_search($letter, $alphabets);
          if ($key - $value < 0) {
            $shift_value = $key - $value + 24;
          } else {
            $shift_value = $key - $value;
          }
          $new_letter = $alphabets[$shift_value];
          array_push($output_array, $new_letter);
      } else {
        array_push($output_array, $letter);
      }
    }
  }

  $outout_string = implode("", $output_array);

  $_SESSION['final_string'] = $outout_string;
  $form_state['redirect'] = 'shift_cipher_success_page';

}

function shift_cipher_success() {
  $answer = $_SESSION['final_string'];
  return 'The output phrase is: <strong>' . $answer . '</strong>';
}
